### ISSUE TITLE
Any particular reason to not use Javalin to render markdown?

### ISSUE THREAD

**Issue by tipsy** [mtso/javalin-maven#1]
Javalin supports rendering markdown (via `ctx.renderMarkdown()`. Did you actively choose to not use this functionality, or were you just not aware of it?

**Comment by mtso** [comment]
Hi @tipsy, I was not aware that Javalin had a commonmark plugin. In the future, my decision to use this functionality would be based on whether or not the template file was stored in a file or in a string.

**Comment by tipsy** [comment]
Allright, thanks :)
